config/routes.rb
Sendgrid::Application.routes.draw do
  resources :inbound_emails

end

app/models/inbound_email.rb
class InboundEmail < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inbound_emails_controller.rb
class InboundEmailsController < ApplicationController
  before_action :set_inbound_email, only: [:show, :edit, :update, :destroy]

  # GET /inbound_emails
  # GET /inbound_emails.json
  def index
    @inbound_emails = InboundEmail.all
  end

  # GET /inbound_emails/1
  # GET /inbound_emails/1.json
  def show
  end

  # GET /inbound_emails/new
  def new
    @inbound_email = InboundEmail.new
  end

  # GET /inbound_emails/1/edit
  def edit
  end

  # POST /inbound_emails
  # POST /inbound_emails.json
  def create
    @inbound_email = InboundEmail.new(inbound_email_params)

    respond_to do |format|
      if @inbound_email.save
        format.html { redirect_to @inbound_email, notice: 'Inbound email was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inbound_email }
      else
        format.html { render action: 'new' }
        format.json { render json: @inbound_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inbound_emails/1
  # PATCH/PUT /inbound_emails/1.json
  def update
    respond_to do |format|
      if @inbound_email.update(inbound_email_params)
        format.html { redirect_to @inbound_email, notice: 'Inbound email was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inbound_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inbound_emails/1
  # DELETE /inbound_emails/1.json
  def destroy
    @inbound_email.destroy
    respond_to do |format|
      format.html { redirect_to inbound_emails_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inbound_email
      @inbound_email = InboundEmail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inbound_email_params
      params.require(:inbound_email).permit(:text, :html, :to, :from, :subject)
    end
end

app/controllers/listener_controller.rb
class ListenerController < ApplicationController
  
    skip_before_filter :verify_authenticity_token

    def receive_email
      @params = params
      #make sure request is a post
      @inbound_email = InboundEmail.new(:text => params["text"],
                              :html => params["html"],
                              :to => clean_field(params["to"]),
                              :from => clean_field(params["from"]),
                              :subject => clean_field(params["subject"])                  )

      respond_to do |format|
         if @inbound_email.save && request.post?
           @inbound_email.process_incoming_email
           flash[:notice] = 'Item was successfully created. '
           format.xml  { render :xml => @inbound_email, :status => :created }
        else
           flash[:notice] = "Oops, we had an error saving the item."
           format.xml  { render :xml => @inbound_email.errors, :status => :unprocessable_entity }
         end
       end
      end
     
     private
     def clean_field(input_string)
         input_string.gsub(/\n/,'') if input_string
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inbound_emails_helper.rb
module InboundEmailsHelper
end

app/views/inbound_emails/_form.html.erb
<%= form_for(@inbound_email) do |f| %>
  <% if @inbound_email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inbound_email.errors.count, "error") %> prohibited this inbound_email from being saved:</h2>

      <ul>
      <% @inbound_email.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :html %><br>
    <%= f.text_area :html %>
  </div>
  <div class="field">
    <%= f.label :to %><br>
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inbound_emails/edit.html.erb
<h1>Editing inbound_email</h1>

<%= render 'form' %>

<%= link_to 'Show', @inbound_email %> |
<%= link_to 'Back', inbound_emails_path %>

app/views/inbound_emails/index.html.erb
<h1>Listing inbound_emails</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Html</th>
      <th>To</th>
      <th>From</th>
      <th>Subject</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inbound_emails.each do |inbound_email| %>
      <tr>
        <td><%= inbound_email.text %></td>
        <td><%= inbound_email.html %></td>
        <td><%= inbound_email.to %></td>
        <td><%= inbound_email.from %></td>
        <td><%= inbound_email.subject %></td>
        <td><%= link_to 'Show', inbound_email %></td>
        <td><%= link_to 'Edit', edit_inbound_email_path(inbound_email) %></td>
        <td><%= link_to 'Destroy', inbound_email, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inbound email', new_inbound_email_path %>

app/views/inbound_emails/new.html.erb
<h1>New inbound_email</h1>

<%= render 'form' %>

<%= link_to 'Back', inbound_emails_path %>

app/views/inbound_emails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @inbound_email.text %>
</p>

<p>
  <strong>Html:</strong>
  <%= @inbound_email.html %>
</p>

<p>
  <strong>To:</strong>
  <%= @inbound_email.to %>
</p>

<p>
  <strong>From:</strong>
  <%= @inbound_email.from %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @inbound_email.subject %>
</p>

<%= link_to 'Edit', edit_inbound_email_path(@inbound_email) %> |
<%= link_to 'Back', inbound_emails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sendgrid</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>